### ISSUE TITLE
MODULE_NOT_FOUND, npm install error

### ISSUE THREAD

**Issue by AxTech212** [utzl/MMM-Solarman#3]
Hello, 

i did everything accordingly to the instructions but it seems there is a problem. The nmp install does not look right to me and when i try to start the mirror it keeps crashing because it does not find the module. 

i have to say i am a absolute amateur, maybe i do something wrong. 

Consoleoutput:
_requireStack: [
    '/magicmirror2/modules/MMM-Solarman/node_helper.js',
    '/magicmirror2/js/app.js',
    '/magicmirror2/serveronly/index.js'
  ]_

**Comment by utzl** [comment]
Hi,
sorry for the late response.
Unfortunaltely I do not know how the npm install works. I wrote the module based on other modules and it worked on my MM.
Could you send me the pm2 log? 
When the module was not found -> make sure the folder name of the module and your entry in config.js are the same.
What versions do you have for npm and node?
Try: 
`node -v`
and
`npm -v`

all the best
Kai

**Comment by andieh** [comment]
hello @AxTech212 
please checkout my branch or wait until @utzl merged the PR. 

package.json file was missing. is working now on my system. thanks!

**Comment by utzl** [comment]
Thanks a lot @andieh !
I merged the pull request.

**Comment by andieh** [comment]
> Thanks a lot @andieh ! I merged the pull request.

nice! i think you can close this ticket then. maybe @AxTech212 can try again
