### ISSUE TITLE
auth invalid token

### ISSUE THREAD

**Issue by Flash11061983** [utzl/MMM-Solarman#6]
After entering my data, “auth invalid token” is displayed in the MagicMirror.

I also get this error on https://reqbin.com/curl.

I tested:

https://globalapi.solarmanpv.com/account/v1.0/token?appId=<appId>&lingual=en&=' \ and

https://api.solarmanpv.com/account/v1.0/token?appId=<appId>&language=en&=' \

Can someone help me with that?

**Comment by utzl** [comment]
Hi, I got an email from Solarman:

"Dear valued user,
     In order to provide you with a better experience, SOLARMAN will upgrade data centers from 2024-01-15 09:00 to 2024-01-15 17:00 (UTC+8).
     During the upgrade, OPENAPI service will be unavailable."

So please try again tomorrow and give feedback to this issue.

**Comment by Flash11061983** [comment]
Hello,
I just tried it again.
Now I get the error message under Run Curl: "msg": "auth invalid appId".
Auth invalid token is still displayed in the MagicMirrow.

Password was converted under SHA256. API key and API ID are available from Solarman.

Url used: https://globalapi.solarmanpv.com/account/v1.0/token?appId=<302309268271864>&language=en&='

greeting

**Comment by utzl** [comment]
Hi,

you have to remove the < and > symbol for your appID.
So use: 
`https://globalapi.solarmanpv.com/account/v1.0/token?appId=302309268271864&language=en&='`
hope this works then

**Comment by Flash11061983** [comment]
Thank you. That seems to have been it.
It worked now.

Now I have the bar in the MagicMirriow: Loading...
Is that right?

**Comment by Flash11061983** [comment]
Thank you for your help, utzl.
The module is now running.
