### ISSUE TITLE
How do I set display language to German?

### ISSUE THREAD

**Issue by dankerthrone** [utzl/MMM-Solarman#8]
Hi,

I had a look through the MMM-Solarman.js file and found that there's a German translation available (also your screenshot ;) ). 

But how do I tell the module to use these translations?

**Comment by dankerthrone** [comment]
-.-

I don't know what's wrong with me, I must've slept bad. Anyway: I edited my config.js to reflect that my language should be "de" and my locale "de-DE".

**Comment by utzl** [comment]
I am glad the module is running on your system.
